metadata:
  name: London KMB Docs
  short_name: lonkmbdocs
  description: >-
    One-stop FAQ for KMB (and Malaysian students) that are pursuing their
    studies in London.
  language: en
  url: 'http://localhost'
  pathPrefix: /
  gaTrackingId: null
  favicon: /assets/favicon.png
  themeColor: '#0066cc'
header:
  enabled: true
  logo: /assets/logo.png
  links: []
sidebar:
  ignoreIndex: false
  forcedNavOrder: []
  expanded: []
  groups: []
  links: []
  poweredBy: {}
  enabled: true
pwa:
  enabled: true
  manifest:
    icon: /assets/logo.png
    display: minimal-ui
    crossOrigin: anonymous
features:
  editOnRepo:
    editable: true
    location: 'http://localhost'
    type: github
  search:
    enabled: false
    indexName: docs
    showStats: true
    pagination:
      enabled: true
  rss:
    enabled: true
    showIcon: true
    copyright: ''
    categories: []
    matchRegex: ^/
    outputPath: /rss.xml
  darkMode:
    enabled: true
    default: false
search:
  enabled: true
  startComponent: icon
  pagination:
    enabled: true
