# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'lonkmbdocs':
  name: lonkmbdocs
  long_name: London KMB Docs
  description: One-stop FAQ for KMB (and Malaysian students) that are pursuing their studies in London.
